# Workflow to lint each pull request to the main branch
name: Lint

on:
  # Runs on pull requests to the main branch
  pull_request: { branches: [main] }

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with: { cache: npm }

    - run: npm ci

    - run: npm run lint
